package:
  name: msmbuilder
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: {{ GIT_DESCRIBE_NUMBER }}
  entry_points:
    - msmb = msmbuilder.scripts.msmb:main


requirements:
  build:
    - python
    - setuptools
    - cython <=0.27.3
    - numpy x.x
    - mdtraj
  run:
    - python
    - setuptools
    - numpy x.x
    - scipy
    - pandas
    - six
    - mdtraj
    - scikit-learn
    - numpydoc
    - pytables
    - pyhmc
    - pyyaml
    - jinja2
    - fastcluster


test:
  requires:
    - nose
    - nose-timer
    - munkres
    - numdifftools
    - statsmodels
    - hmmlearn=0.2.1
    - cvxpy # [not win]
    - msmb_data
  imports:
    - msmbuilder
  commands:
    - msmb -h
    - nosetests msmbuilder -v --with-timer --timer-ok 2 --timer-warning 10 --timer-filter error


about:
  home: https://github.com/msmbuilder/msmbuilder
  license: LGPLv2.1+
  summary: 'MSMBuilder: Statistical models for biomolecular dynamics'
